// Original teaching scripts derived from the supplied Ridgway Knight transcripts.
export const UNITS = [
 {id:'balance',title:'The equation underneath it all',short:'Assets, liabilities & equity',icon:'=',group:'01 · EQUATION CONTROL',audio:'equations',formula:'Assets = Liabilities + Equity',rule:'Assets are what the business owns. Liabilities are what it owes. Equity is what remains for the owner.',example:['Assets are $18,000 and liabilities are $7,000. Find equity.','18,000 = 7,000 + Equity','Subtract 7,000 from BOTH sides.','11,000 = Equity. Check: 18,000 = 7,000 + 11,000.'],trap:'Use amounts from the same date. Beginning assets minus ending liabilities does not give you beginning or ending equity.'},
 {id:'equity',title:'Stop guessing which sign changes',short:'Beginning & ending equity',icon:'↔',group:'01 · EQUATION CONTROL',audio:'equations',formula:'Beginning Equity + Investment + Income − Withdrawals = Ending Equity',rule:'An equals sign says both sides have the same value. To keep that true, do the same operation to BOTH sides. “Moving” a term is shorthand for undoing it on both sides.',example:['Beginning equity is unknown. Investment is $2,000, income is $5,000, withdrawals are $1,000, and ending equity is $16,000.','Beginning Equity + 2,000 + 5,000 − 1,000 = 16,000','Subtract 2,000 and 5,000 from both sides. Add 1,000 to both sides.','Beginning Equity = 16,000 − 2,000 − 5,000 + 1,000 = 10,000.','Check forward: 10,000 + 2,000 + 5,000 − 1,000 = 16,000.'],trap:'Withdrawals are subtracted in the ORIGINAL equation. If withdrawals are the missing item, add Withdrawals to both sides, then subtract Ending Equity. Withdrawals = Beginning + Investment + Income − Ending.'},
 {id:'income',title:'Revenue is not the same as income',short:'Revenue, expenses & losses',icon:'−',group:'01 · EQUATION CONTROL',audio:'equations',formula:'Revenue − Expenses = Net Income',rule:'Income is what remains after expenses. A loss is negative income. Owner investment is not revenue, and withdrawals are not expenses.',example:['Revenue is $9,000; expenses are $12,000.','9,000 − 12,000 = −3,000: a $3,000 net loss.','In the equity equation, adding income of −3,000 means equity falls by 3,000.'],trap:'Cash received is not automatically revenue. Borrowing and owner investment bring in cash without creating income.'},
 {id:'supplies',title:'What you started with',short:'Supplies balances',icon:'□',group:'02 · BEGINNING TO ENDING',audio:'balances',formula:'Beginning Supplies + Purchases − Supplies Used = Ending Supplies',rule:'Start with the supplies already there. Add new supplies. Subtract what got used. Whatever remains is the ending balance.',example:['Ending supplies: $3,400. Purchases: $18,700. Used: $21,100. Find beginning supplies.','Beginning + 18,700 − 21,100 = 3,400','Beginning = 3,400 − 18,700 + 21,100 = 5,800.','Check: 5,800 + 18,700 − 21,100 = 3,400.'],trap:'Purchasing supplies creates an asset. Using supplies creates an expense and reduces the supplies asset.'},
 {id:'receivables',title:'Money customers still owe you',short:'Accounts Receivable',icon:'↓',group:'02 · BEGINNING TO ENDING',audio:'balances',formula:'Beginning Accounts Receivable + Sales on Account − Collections = Ending Accounts Receivable',rule:'Sales on account increase what customers owe. Collections reduce what customers owe. Here, assume no write-offs or returns.',example:['Customers owed $4,000 at the beginning. New sales on account were $9,000. They owe $3,000 at the end.','4,000 + 9,000 − Collections = 3,000','Collections = 4,000 + 9,000 − 3,000 = 10,000.'],trap:'A collection on account is not new revenue. Revenue was recorded when the service was performed.'},
 {id:'payables',title:'Money your business still owes',short:'Accounts Payable',icon:'↑',group:'02 · BEGINNING TO ENDING',audio:'balances',formula:'Beginning Accounts Payable + Purchases on Account − Payments = Ending Accounts Payable',rule:'Purchases on account add to your debt. Payments reduce your debt. Here, assume no returns or other changes.',example:['Beginning payable: $22,100. Purchases on account: $90,800. Ending payable: $30,300.','22,100 + 90,800 − Payments = 30,300','Add Payments to both sides, then subtract 30,300.','Payments = 22,100 + 90,800 − 30,300 = 82,600.'],trap:'Paying an old account payable reduces a liability. It does not record the original expense a second time.'},
 {id:'bridge',title:'Connect the equations',short:'Professor-style multi-step problems',icon:'⋈',group:'03 · PUT IT TOGETHER',audio:'bridge',formula:'Find equity at each date → account for changes → solve the missing item',rule:'Start where the information is complete. If beginning assets and liabilities are known, calculate beginning equity. If ending assets and liabilities are known, calculate ending equity. Then use the equity equation.',example:['Beginning assets: $55,000; beginning liabilities: $24,500. Investment: $6,000; income: $8,500; withdrawals: $3,500. Ending assets: $58,000. Find ending liabilities.','Beginning Equity = 55,000 − 24,500 = 30,500.','Ending Equity = 30,500 + 6,000 + 8,500 − 3,500 = 41,500.','Ending Liabilities = 58,000 − 41,500 = 16,500.'],trap:'You do not always start with ending equity. Start with whichever date has enough information, and work toward what the question asks.'},
 {id:'transactions',title:'Read the story before the entry',short:'Transaction analysis',icon:'⇄',group:'04 · TRANSACTION INSTINCTS',audio:'transactions',formula:'Financial position → account names → debit and credit',rule:'First ask what changes for the BUSINESS. Then name the accounts. Only then decide which account gets the debit or credit.',example:['The business collects $900 from a customer who already owed it.','Cash increases $900; Accounts Receivable decreases $900. Both are assets.','Total assets do not change. Liabilities and equity do not change.','Debit Cash $900; credit Accounts Receivable $900.'],trap:'“On account” means payment occurs at a different time. Ask who owes whom: customers owe you = receivable; you owe suppliers = payable.'},
 {id:'normal',title:'Debit is a side, not a synonym for up',short:'Debits, credits & normal balances',icon:'T',group:'04 · TRANSACTION INSTINCTS',audio:'transactions',formula:'Debit increases: Assets, Expenses, Withdrawals. Credit increases: Liabilities, Capital, Revenue.',rule:'Debit means left. Credit means right. The type of account decides which side increases it. Expenses and withdrawals reduce equity, but their own accounts increase with debits.',example:['You incur $800 of rent expense and will pay later.','Rent Expense increases: debit Rent Expense $800.','Accounts Payable increases: credit Accounts Payable $800.','Liabilities increase $800 and equity decreases $800.'],trap:'Never use “debit means increase” by itself. Ask: increase in WHICH type of account?'},
 {id:'ledger',title:'Follow an entry into the ledger',short:'Posting & balances',icon:'≡',group:'05 · CLOSE THE LOOP',audio:'ledger',formula:'Beginning Balance + Increases − Decreases = Ending Balance',rule:'The journal lists transactions in date order. The ledger groups them by account. Posting means copying each debit and credit to the same side of its ledger account.',example:['Cash begins with a $2,000 debit balance. Debits during the month: $5,000. Credits: $3,000.','Cash ends at 2,000 + 5,000 − 3,000 = $4,000 debit.','For a liability with a normal credit balance, add credits and subtract debits instead.'],trap:'A normal balance is typical, not guaranteed. If credits exceed all debits in an asset account, its actual balance is a credit.'},
 {id:'trial',title:'Check the ledger, then build statements',short:'Trial balance & statements',icon:'✓',group:'05 · CLOSE THE LOOP',audio:'ledger',formula:'Total debit balances = Total credit balances',rule:'A trial balance checks whether ledger debits equal ledger credits. Prepare the income statement first, the equity statement next, and then the balance sheet.',example:['Revenue: $12,000. Expenses: $7,000. Beginning equity: $8,000. Investment: $2,000. Withdrawals: $1,000.','Income = 12,000 − 7,000 = 5,000.','Ending Equity = 8,000 + 2,000 + 5,000 − 1,000 = 14,000.','Carry $14,000 ending equity to the balance sheet.'],trap:'A balanced trial balance does not prove every entry is correct. Omitting an entire transaction, or using the wrong accounts with equal debits and credits, can leave it balanced.'}
];
export const AUDIO_LESSONS = [
 {id:'equations',title:'01 · Why the signs change',subtitle:'A calm walkthrough of both sides of the equation.',segments:[
 {text:'Welcome to Ledger. This is an AI narrated accounting lesson. You do not need to look at your screen. We will work through the reasoning, then I will ask you to answer out loud. Pause whenever you want more time. First: an equals sign means both sides have the same value. There is no magic flip rule. When you subtract the same amount from both sides, the equation stays balanced. Assets equals liabilities plus equity. Imagine assets of eighteen thousand dollars and liabilities of seven thousand dollars. Eighteen thousand equals seven thousand plus equity. Subtract seven thousand from both sides. Equity is eleven thousand. Check by adding seven thousand and eleven thousand. You are back at eighteen thousand.'},
 {text:'Now the equation you have been finding confusing. Beginning equity, plus owner investment, plus income, minus withdrawals, equals ending equity. Say it with me: start, add investment, add income, subtract withdrawals, finish. Suppose beginning equity is ten thousand, investment is two thousand, income is five thousand, and withdrawals are one thousand. What is ending equity? Think through the story.',pause:7},
 {text:'Sixteen thousand dollars. Ten plus two plus five minus one, in thousands. You started at the beginning because you were solving for the ending. Now turn that SAME story around. You know ending equity is sixteen thousand, investment is two thousand, income is five thousand, and withdrawals are one thousand. Beginning equity is missing. Write the original equation in your mind. Beginning, plus two, plus five, minus one, equals sixteen. All amounts are in thousands. Undo plus two by subtracting two from BOTH sides. Undo plus five by subtracting five from BOTH sides. Undo minus one by adding one to BOTH sides. Beginning equity is sixteen minus two minus five plus one. Ten thousand. We are undoing the changes to go backward.'},
 {text:'Here is the part to be careful with. If WITHDRAWALS is missing, do not use that same list of signs. Beginning plus investment plus income minus withdrawals equals ending. Add withdrawals to BOTH sides. Now beginning plus investment plus income equals ending plus withdrawals. Subtract ending from BOTH sides. Withdrawals equals beginning plus investment plus income minus ending. Try it: beginning equity ten thousand, investment two thousand, income five thousand, ending equity sixteen thousand. How much was withdrawn?',pause:7},
 {text:'One thousand. Ten plus two plus five minus sixteen. Finally, revenue minus expenses equals income. Revenue is NOT the same thing as income. Nine thousand in revenue minus twelve thousand in expenses is negative three thousand: a three thousand dollar loss. In the equity equation, adding income of negative three thousand reduces equity. Investment is not revenue. Withdrawals are not an expense. Your routine is: write the original equation, identify what is missing, do the same operation on both sides, calculate, and check in the original equation. Do a few fresh questions after this lesson. Hearing the method is the start; retrieving it yourself is the practice.'}
 ]},
 {id:'balances',title:'02 · Beginning, increases, decreases, ending',subtitle:'Supplies, collections, and payments without memorizing three new rules.',segments:[
 {text:'Think of a bucket. Start with what is inside. Add what comes in. Subtract what leaves. What is left is the ending balance. Accounting uses that same story. Beginning balance plus increases minus decreases equals ending balance. For supplies: beginning supplies plus purchases minus supplies used equals ending supplies. Purchases put supplies in the bucket. Using supplies takes them out.'},
 {text:'Here is a problem like the one you were working on. Supplies ended at three thousand four hundred dollars. Purchases were eighteen thousand seven hundred. Supplies used were twenty one thousand one hundred. Beginning supplies is missing. Ask what we are looking for: the START. Beginning plus eighteen thousand seven hundred minus twenty one thousand one hundred equals three thousand four hundred. To isolate beginning, subtract purchases from both sides and add supplies used to both sides. Beginning equals three thousand four hundred minus eighteen thousand seven hundred plus twenty one thousand one hundred. That gives five thousand eight hundred. Check forward: five thousand eight hundred plus eighteen thousand seven hundred minus twenty one thousand one hundred equals three thousand four hundred.'},
 {text:'Try an easier version out loud. Ending supplies is four hundred dollars. Purchases were nine hundred. Supplies used were twelve hundred. What were beginning supplies? Work backward from the ending amount.',pause:9},
 {text:'Seven hundred dollars. Four hundred minus nine hundred plus twelve hundred. Now Accounts Receivable means money customers owe your business. Beginning receivable plus sales on account minus collections equals ending receivable. When you collect an old customer balance, cash goes up and receivable goes down. You do not earn that revenue again. Suppose customers owed four thousand at the beginning, new sales on account were nine thousand, and customers owe three thousand at the end. Collections equals four thousand plus nine thousand minus three thousand. Ten thousand dollars was collected.'},
 {text:'Accounts Payable means money your business owes suppliers. Beginning payable plus purchases on account minus payments equals ending payable. Beginning was twenty two thousand one hundred dollars. Purchases on account were ninety thousand eight hundred. Ending was thirty thousand three hundred. Payments is the missing decrease. Add payments to both sides, then subtract the ending balance from both sides. Payments equals beginning plus purchases minus ending. Twenty two thousand one hundred plus ninety thousand eight hundred minus thirty thousand three hundred is eighty two thousand six hundred dollars.'},
 {text:'Quick check. Your business owed one thousand dollars, bought two thousand more on account, and now owes eight hundred. How much did it pay?',pause:7},
 {text:'Two thousand two hundred dollars. One thousand plus two thousand minus eight hundred. Keep this distinction: a payment on account reduces an old liability. It is not automatically a new expense. A collection on account reduces an old receivable. It is not new revenue. For all three balance stories, choose the account, identify what increases and decreases it, then solve the same beginning to ending equation.'}
 ]},
 {id:'bridge',title:'03 · Where do I start?',subtitle:'Connect beginning equity, ending equity, and the missing amount.',segments:[
 {text:'This lesson combines the equations the way your professor does. Your first job is not to guess whether to start with beginning or ending equity. Your first job is to find a place where you have enough information. Assets minus liabilities gives equity, but all three amounts must be from the SAME date. Beginning assets minus beginning liabilities gives beginning equity. Ending assets minus ending liabilities gives ending equity.'},
 {text:'Let us solve for ending liabilities. Beginning assets are fifty five thousand dollars. Beginning liabilities are twenty four thousand five hundred. The owner invested six thousand, the company earned eight thousand five hundred, and the owner withdrew three thousand five hundred. Ending assets are fifty eight thousand. Step one: find beginning equity. Fifty five thousand minus twenty four thousand five hundred equals thirty thousand five hundred. Step two: use the changes to find ending equity. Thirty thousand five hundred plus six thousand plus eight thousand five hundred minus three thousand five hundred equals forty one thousand five hundred. Step three: ending liabilities equals ending assets minus ending equity. Fifty eight thousand minus forty one thousand five hundred equals sixteen thousand five hundred.'},
 {text:'Now imagine the question asks for BEGINNING liabilities. You know beginning assets, but not beginning equity. You do know ending assets and ending liabilities. Start with those ending numbers to find ending equity. Then work backward: beginning equity equals ending equity minus investment minus income plus withdrawals. Finally, beginning liabilities equals beginning assets minus beginning equity. You start at the end here because that is where the information is complete, not because every question starts at the end.'},
 {text:'A smaller example. Ending assets are twenty thousand dollars. Ending liabilities are eight thousand. The owner invested two thousand, income was three thousand, and withdrawals were one thousand. Beginning assets were fifteen thousand. First, what is ENDING equity?',pause:6},
 {text:'Twelve thousand. Twenty thousand minus eight thousand. Now work backward. What is BEGINNING equity? Ending twelve thousand minus investment two thousand minus income three thousand plus withdrawals one thousand.',pause:8},
 {text:'Eight thousand. Now beginning assets were fifteen thousand. What were beginning liabilities?',pause:6},
 {text:'Seven thousand. Fifteen thousand minus eight thousand. You just connected three steps. Another common problem gives assets and liabilities at BOTH dates and asks for income. Calculate both equity amounts first. Then income equals ending equity minus beginning equity minus investment plus withdrawals. If the result is negative, that is a loss. Ask yourself before each calculation: what date am I using, what do I already know, and what number does the next step need?'}
 ]},
 {id:'transactions',title:'04 · Who owes whom?',subtitle:'Collection, payment, advances, expenses, and compound entries.',segments:[
 {text:'We will use your professor’s three steps: financial position, account names, then debit and credit. First, the business collects nine hundred dollars from a customer who already owed it. Think before the entry. Cash increases. Accounts Receivable decreases. Both are assets, so total assets stays the same. Liabilities and equity do not change. Now the entry: debit Cash, nine hundred. Credit Accounts Receivable, nine hundred. Revenue was already earned when the service was performed.'},
 {text:'Now your business pays nine hundred dollars on an old supplier balance. Which two accounts change, and do they increase or decrease?',pause:7},
 {text:'Cash decreases and Accounts Payable decreases. Total assets and total liabilities decrease equally. Debit Accounts Payable. Credit Cash. Paying an old bill is not a new expense. Compare that with using electricity today and agreeing to pay next month. Now an expense is incurred, and a liability is created. Debit Utilities Expense and credit Accounts Payable. The expense reduces equity, even though cash has not moved.'},
 {text:'Debit means left. Credit means right. They do not always mean increase or decrease. Assets, expenses, and withdrawals increase with debits. Liabilities, capital, and revenue increase with credits. The opposite side decreases each account. Expenses reduce equity, but the expense account itself increases with a debit. That is why you cannot treat every equity related account the same way.'},
 {text:'A customer pays five hundred dollars BEFORE you do the work. Is that revenue right now?',pause:5},
 {text:'No. Cash increases and a liability called Unearned Revenue increases. Debit Cash; credit Unearned Revenue. After the work is completed, debit Unearned Revenue to remove the obligation and credit Revenue because it is now earned. Owner investment is another cash receipt that is not revenue. It increases Cash and Capital. Borrowing cash increases Cash and Notes Payable. Owner withdrawals reduce Cash and equity but are not business expenses.'},
 {text:'Last example. Equipment costs ten thousand dollars. The business pays four thousand now and owes six thousand on account. Equipment goes up by the FULL ten thousand. Cash goes down by four thousand. Accounts Payable goes up by six thousand. Net assets increase six thousand, matching the increase in liabilities. Debit Equipment ten thousand. Credit Cash four thousand. Credit Accounts Payable six thousand. Ten thousand in debits equals ten thousand in credits. Every entry has equal total debits and credits; it does not need the same number of accounts on each side. Try describing the story before saying debit or credit. That is the skill we are building.'}
 ]},
 {id:'ledger',title:'05 · From the story to the statements',subtitle:'Journal, ledger, trial balance, income, and equity.',segments:[
 {text:'Here is the order from your professor’s recordings. Analyze the transaction. Record it in the journal. Post it to the ledger. Prepare a trial balance. The journal is a chronological record: what happened in date order. The ledger groups the activity by account, so we can find each account’s balance. Posting means copying. A debit in the journal remains a debit in the ledger. A credit stays a credit. We do not switch sides when posting.'},
 {text:'Cash is an asset, so its normal balance is a debit. Suppose beginning cash is two thousand dollars, debits during the month are five thousand, and credits are three thousand. Ending cash equals two thousand plus five thousand minus three thousand. Four thousand debit. Now a payable normally has a credit balance. Beginning payable plus credits minus debits gives its ending balance on the normal credit side. If a calculation comes out negative, the actual balance is on the opposite side. Normal means usual, not guaranteed.'},
 {text:'Which report checks whether the total debit balances and total credit balances in the ledger are equal?',pause:5},
 {text:'The trial balance. It lists accounts and their balances at a particular date. Group assets first, then liabilities, then capital, withdrawals, revenues, and expenses. Copy the ACTUAL balance to the correct debit or credit column. Equal totals are useful, but they do not prove every transaction is correct. If a whole entry was omitted, both totals could still agree. If the wrong accounts were used but debits and credits were equal, the trial balance could still balance.'},
 {text:'The trial balance also helps prepare statements. Prepare the income statement first: revenue minus expenses equals income. Next the equity statement: beginning equity plus investment plus income minus withdrawals equals ending equity. Then the balance sheet: assets equals liabilities plus ending equity. In an unclosed capital account, the balance can include beginning capital plus additional owner investment. Do not count the investment twice when preparing the equity statement.'},
 {text:'Try the flow. Revenue twelve thousand, expenses seven thousand. Beginning equity eight thousand, owner investment two thousand, withdrawals one thousand. What is income?',pause:5},
 {text:'Five thousand. Now add that income to beginning equity and investment, then subtract withdrawals. What is ending equity?',pause:7},
 {text:'Fourteen thousand. Eight plus two plus five minus one, in thousands. That fourteen thousand goes to the equity section of the balance sheet. Remember the difference between a period and a date: an income statement covers activity during a period. A balance sheet shows financial position at a date. End this lesson by doing a short mixed practice session. Explain each answer in your own words before looking at the explanation.'}
 ]}
];
export const CARDS = UNITS.flatMap(u=>[
 {id:u.id+'-rule',unit:u.id,front:u.short+': what is the rule?',back:u.formula+' '+u.rule},
 {id:u.id+'-trap',unit:u.id,front:'What should I watch out for with '+u.short.toLowerCase()+'?',back:u.trap}
]);
