import { UNITS, AUDIO_LESSONS, CARDS } from './mastery-content.js';
import { selectQuestion,generate,isCorrect,record,cash,shuffle } from './mastery-engine.js';
const app=document.querySelector('#masteryApp'),KEY='ledger-academy-v1';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const empty=()=>({xp:0,patterns:{},read:{},cards:{},daily:{},attempts:0,clean:0});
function validState(s){
 if(!s||typeof s!=='object'||!['xp','attempts','clean'].every(k=>Number.isFinite(s[k])&&s[k]>=0))return false;
 if(!['patterns','cards','daily','read'].every(k=>s[k]&&typeof s[k]==='object'&&!Array.isArray(s[k])))return false;
 if(!Object.values(s.daily).every(v=>Number.isFinite(v)&&v>=0)||!Object.values(s.read).every(v=>typeof v==='boolean'))return false;
 for(const [key,p] of Object.entries(s.patterns)){
  if(!p||!UNITS.some(u=>u.id===p.unit)||!key.startsWith(p.unit+':')||!['attempts','correct','run','due'].every(k=>Number.isFinite(p[k])&&p[k]>=0))return false;
  if(['balance','income','equity','supplies','receivables','payables'].includes(p.unit)){const index=Number(key.split(':')[1]),length=p.unit==='equity'?5:['balance','income'].includes(p.unit)?3:4;if(!Number.isInteger(index)||index<0||index>=length)return false;}
 }
 for(const [key,p] of Object.entries(s.cards))if(!CARDS.some(c=>c.id===key)||!p||!Number.isFinite(p.run)||p.run<0||!Number.isFinite(p.due)||p.due<0)return false;
 return true;
}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));return validState(s)?{...empty(),...s}:empty();}catch{return empty();}}
let state=load(),view='path',session=null,cardQueue=[],card=null,revealed=false,manifest=null,playing=null;
const date=()=>new Date().toLocaleDateString('en-CA');
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{toast('Your browser could not save progress. Export a backup.');}$('#xp').textContent=state.xp+' XP';}
function toast(s){$('#status').textContent=s;$('#status').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#status').classList.remove('show'),3500);}
function nav(v){view=v;stopDeviceVoice();document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));({path:renderPath,practice:renderPracticeMenu,cards:renderCards,listen:renderListen})[v]();app.focus({preventScroll:true});window.scrollTo(0,0);}
const button=(text,action,cls='')=>`<button type="button" class="btn ${cls}" data-action="${action}">${text}</button>`;
function bind(actions){Object.entries(actions).forEach(([key,fn])=>app.querySelectorAll(`[data-action="${key}"]`).forEach(b=>b.onclick=fn));}
function unitStatus(id){const rows=Object.values(state.patterns).filter(p=>p.unit===id);const attempts=rows.reduce((a,p)=>a+p.attempts,0),clean=rows.reduce((a,p)=>a+p.correct,0);return {attempts,clean,due:rows.filter(p=>p.due<=Date.now()).length};}
function renderPath(){
 const due=Object.values(state.patterns).filter(p=>p.due<=Date.now()).length,today=state.daily[date()]||0;
 app.innerHTML=`<section class="hero"><div><span class="eyebrow">YOUR ACCOUNTING COMEBACK</span><h1>Less guessing.<br><em>More “I get it.”</em></h1><p>One small lesson. A few fresh questions. Build the equation and transaction instincts you need, one step at a time.</p><div class="actions">${button(session?'Continue your session':'Start my 8-question session','start','primary')}${button('Listen & learn','listen')}</div><p class="micro">Built around your professor’s method · No lives to lose</p></div><div class="orbit-card"><span class="eyebrow">KEEP BOTH SIDES EQUAL</span><div class="scale"><span>? + 7</span><b>=</b><span>18</span></div><div class="line"></div><p>Subtract 7 from <b>both</b> sides.<br>The missing piece is 11. You know why.</p></div></section>
 <div class="metrics"><div class="metric"><strong>${today}/8</strong><small>QUESTIONS TODAY</small></div><div class="metric"><strong>${due}</strong><small>PATTERNS TO REVIEW</small></div><div class="metric"><strong>${state.attempts?Math.round(100*state.clean/state.attempts):0}%</strong><small>WITHOUT HELP</small></div></div>
 <div class="layout"><section><div class="section-title"><h2>Your learning path</h2><span class="micro">Go at your pace</span></div>${UNITS.map((u,i)=>{const stats=unitStatus(u.id);return `${i===0||UNITS[i-1].group!==u.group?'<div class="group-label">'+u.group+'</div>':''}<button class="unit ${stats.clean>=3?'done':''}" data-unit="${u.id}"><span class="node">${stats.clean>=3?'✓':u.icon}</span><span><strong>${u.short}</strong><small>${stats.attempts?stats.clean+' / '+stats.attempts+' answered without help':state.read[u.id]?'Lesson read · Try it yourself':'Learn → guided practice → recall'}${stats.due?' · Review due':''}</small></span><span class="arrow">↗</span></button>`;}).join('')}</section>
 <aside><div class="card"><span class="eyebrow">YOUR NEXT FOUR STUDY SESSIONS</span><div class="day"><b>DAY 1</b><span>Equations + beginning and ending balances</span></div><div class="day"><b>DAY 2</b><span>Transactions + debit and credit reasoning</span></div><div class="day"><b>DAY 3</b><span>Multi-step problems + journals + trial balance</span></div><div class="day"><b>DAY 4</b><span>Mixed recall + the original test simulator</span></div><a class="btn quiet" href="index.html">Open original Ledger trainer ↗</a></div><div class="card side-note" style="margin-top:18px"><h3>“When do I start at the end?”</h3><p>When the ending information lets you find a number you need. Start with what you know. Work toward what is missing.</p>${button('Show me how','bridge')}</div></aside></div><p class="source">Lesson wording and examples are based on your supplied Ridgway Knight course transcripts. Practice progress is not a prediction of your test score. Progress stays in this browser.</p><div class="backup">${button('Export progress','export')}${button('Import progress','import')}<input type="file" id="backupInput" accept="application/json" hidden></div>`;
 bind({start:()=>session?renderQuestion():startSession(),listen:()=>nav('listen'),bridge:()=>renderLesson('bridge'),export:exportProgress,import:()=>$('#backupInput').click()});
 app.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>renderLesson(b.dataset.unit));$('#backupInput').onchange=importProgress;
}
function renderLesson(id,fromQuestion=false){const u=UNITS.find(u=>u.id===id);view='path';
 app.innerHTML=`<section class="narrow lesson"><button class="back" id="lessonBack">← ${fromQuestion?'Back to my question':'Learning path'}</button><div class="eyebrow">${esc(u.group)} · SMALL LESSON</div><h1 style="font-size:40px">${esc(u.title)}</h1><p>${esc(u.rule)}</p><div class="formula">${esc(u.formula)}</div><div class="section-title"><h2>Walk through one</h2></div><div class="card">${u.example.map((x,i)=>`<div class="step-line"><span class="number">${i+1}</span><p>${esc(x)}</p></div>`).join('')}</div><div class="trap"><strong>The common mix-up</strong>${esc(u.trap)}</div><div class="actions">${button(fromQuestion?'Return to question':'I get it · Practice','practiceLesson','primary')}${button('Listen to this topic','listenTopic')}</div></section>`;
 $('#lessonBack').onclick=()=>fromQuestion?renderQuestion():nav('path');bind({practiceLesson:()=>{state.read[id]=true;save();fromQuestion?renderQuestion():startSession(id);},listenTopic:()=>{nav('listen');document.getElementById('track-'+u.audio)?.scrollIntoView({block:'center'});}});window.scrollTo(0,0);
}
function renderPracticeMenu(){app.innerHTML=`<section class="narrow"><span class="eyebrow">FRESH NUMBERS. SAME REASONING.</span><h1 style="font-size:45px">Make the method stick.</h1><p>Guided mode checks your thinking one step at a time. Recall mode asks for the final result first. Misses return as fresh questions, with the same missing item or transaction pattern.</p><div class="mode-row"><label for="practiceMode">How much help?</label><select id="practiceMode"><option value="guided">Guided · every step</option><option value="recall">Recall · try it myself</option></select></div><div class="actions">${button('Adapt to my weak spots','mixed','primary')}${session?button('Resume current session','resume'):''}</div><div class="section-title"><h2>Or focus on one skill</h2></div>${UNITS.map(u=>`<button class="unit" data-practice="${u.id}"><span class="node">${u.icon}</span><span><strong>${u.short}</strong><small>${esc(u.title)}</small></span><span class="arrow">→</span></button>`).join('')}</section>`;bind({mixed:()=>startSession(null,$('#practiceMode').value),resume:renderQuestion});app.querySelectorAll('[data-practice]').forEach(b=>b.onclick=()=>startSession(b.dataset.practice,$('#practiceMode').value));}
function startSession(unit=null,mode='guided'){session={unit,mode,done:0,clean:0,queue:[],q:null,step:0,failed:false,assisted:false,feedback:null,selected:null,hint:false};nextQuestion();}
function nextQuestion(){const s=session;s.q=s.queue.length?generate(s.queue[0].unit,s.queue.shift().pattern):selectQuestion(state,s.unit);s.step=s.mode==='recall'?s.q.stages.length-1:0;s.failed=false;s.assisted=false;s.feedback=null;s.selected=null;s.hint=false;renderQuestion();}
function renderQuestion(){if(!session)return renderPracticeMenu();view='practice';document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.view==='practice'));const s=session,q=s.q,step=q.stages[s.step],unit=UNITS.find(u=>u.id===q.unit),fb=s.feedback;
 app.innerHTML=`<section class="narrow"><div class="drill-head"><button class="back" id="exitSession">← Save & leave</button><span class="pill">${s.done+1} / 8 · ${s.mode==='recall'?'RECALL':'GUIDED'}</span></div><div class="mini-bar"><span style="width:${s.done/8*100}%"></span></div><div class="card question"><div class="eyebrow">${esc(unit.short)}</div><h2 style="margin-top:14px">${esc(q.title)}</h2><p class="story">${esc(q.prompt)}</p>${q.terms&&s.mode==='guided'?`<div class="term-grid">${q.terms.map(t=>`<div class="term ${t.unknown?'target':''}">${esc(t.label)}<strong>${t.unknown?'Find this':cash(t.value)}</strong></div>`).join('')}</div>`:''}<div class="steps" aria-label="Step ${s.step+1} of ${q.stages.length}">${q.stages.map((_,i)=>`<span class="${i<s.step?'passed':i===s.step?'current':''}"></span>`).join('')}</div><h2>${esc(step.prompt)}</h2><form id="answerForm">${step.options?'<div class="choices" role="group" aria-label="Answer choices">'+step.options.map((o,i)=>`<button type="button" class="choice ${s.selected===o?'selected':''} ${fb&&o===step.answer?'correct':''} ${fb&&!fb.ok&&s.selected===o?'incorrect':''}" data-choice="${i}" ${fb?'disabled':''} aria-pressed="${s.selected===o}">${esc(o)}</button>`).join('')+'</div>':`<label class="answer-label" for="numberAnswer">Dollar amount · use a minus sign for a loss</label><input id="numberAnswer" class="numeric" inputmode="text" autocomplete="off" placeholder="Your answer" value="${esc(s.selected||'')}" ${fb?'disabled':''}>`}${fb?`<div class="feedback ${fb.ok?'':'wrong'}" role="status"><h3>${fb.ok?'That’s it.':'Let’s make this click.'}</h3><p>${!fb.ok?'Correct answer: '+esc(typeof step.answer==='number'?cash(step.answer):step.answer)+'\n\n':''}${esc(step.why)}</p></div>`:''}${s.hint?`<div class="hint">${esc(unit.rule)}<br><strong>${esc(unit.formula)}</strong></div>`:''}<div class="actions">${fb?'<button type="button" class="btn primary" id="nextStep">'+(s.step===q.stages.length-1?'Finish question →':'Next step →')+'</button>':'<button class="btn primary" type="submit">Check answer</button>'}${!fb?button('Give me a hint','hint','quiet'):''}${button('Review lesson','review','quiet')}</div></form>${fb&&s.step===q.stages.length-1?`<details class="worked"><summary>Show the full worked solution</summary>${q.worked.map(w=>`<div class="step-line"><p><strong>${esc(w.action)}</strong><br>${esc(w.equation)}</p></div>`).join('')}</details>`:''}</div><p class="micro" style="margin:15px 0">${s.mode==='guided'?'Get the reasoning right before the next step.':'Recall mode hides the intermediate steps until you check.'} Hints and lesson reviews count as assisted practice.</p></section>`;
 $('#exitSession').onclick=()=>nav('path');app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{s.selected=step.options[Number(b.dataset.choice)];renderQuestion();});$('#numberAnswer')?.addEventListener('input',e=>s.selected=e.target.value);
 $('#answerForm').onsubmit=e=>{e.preventDefault();if(s.feedback)return;if(s.selected===null||String(s.selected).trim()===''){toast('Choose an answer or enter an amount first.');return;}const ok=isCorrect(step,String(s.selected));s.failed ||= !ok;s.feedback={ok};renderQuestion();};
 bind({hint:()=>{s.assisted=true;s.hint=true;renderQuestion();},review:()=>{s.assisted=true;renderLesson(q.unit,true);}});
 $('#nextStep')?.addEventListener('click',()=>{if(s.step<q.stages.length-1){s.step++;s.selected=null;s.feedback=null;s.hint=false;renderQuestion();}else finishQuestion();});
}
function finishQuestion(){const s=session,clean=!s.failed&&!s.assisted;record(state,s.q,clean);s.done++;s.clean+=clean?1:0;state.attempts++;state.clean+=clean?1:0;state.xp+=clean?15:5;state.daily[date()]=(state.daily[date()]||0)+1;if(!clean&&s.queue.length<4)s.queue.push({unit:s.q.unit,pattern:s.q.pattern},{unit:s.q.unit,pattern:s.q.pattern});save();if(s.done>=8)finishSession();else nextQuestion();}
function finishSession(){const s=session;app.innerHTML=`<section class="narrow card finish"><div class="medal">✦</div><span class="eyebrow">ONE SESSION STRONGER</span><h1 style="font-size:40px">${s.clean>=6?'It’s starting to click.':'You’re learning the method.'}</h1><p>You completed 8 questions.<br><strong>${s.clean} answered without hints or corrections.</strong><br>${8-s.clean?`${8-s.clean} assisted or corrected. Those patterns are saved for review.`:'Come back later to check that it stuck.'}</p><div class="actions">${button('Another 8','again','primary')}${button('Back to my path','path')}</div></section>`;const unit=s.unit,mode=s.mode;session=null;bind({again:()=>startSession(unit,mode),path:()=>nav('path')});window.scrollTo(0,0);}
function renderCards(){if(!cardQueue.length)cardQueue=shuffle(CARDS.filter(c=>!state.cards[c.id]||state.cards[c.id].due<=Date.now()));if(!cardQueue.length){app.innerHTML=`<section class="narrow card finish"><h2>Cards caught up.</h2><p>Your next reviews are scheduled. Practice fresh questions while the cards rest.</p>${button('Review all anyway','all','primary')}</section>`;bind({all:()=>{cardQueue=shuffle(CARDS);card=null;renderCards();}});return;}if(!card)card=cardQueue[0];app.innerHTML=`<section class="narrow"><span class="eyebrow">SAY IT BEFORE YOU FLIP IT</span><div class="section-title"><h2>Quick recall</h2><span class="pill">${cardQueue.length} left</span></div><p>Explain it out loud, then check yourself. Card confidence is tracked separately from question accuracy.</p><button class="flashcard ${revealed?'revealed':''}" id="flipCard"><small>${revealed?'THE IDEA':'TAP TO REVEAL'}</small>${esc(revealed?card.back:card.front)}</button><div class="flash-actions">${revealed?button('Need this again','again')+button('Got it','got','primary'):button('Reveal answer','flip','primary')}</div>${revealed?'<div class="flash-actions">'+button('Practice this skill','skill','quiet')+'</div>':''}</section>`;$('#flipCard').onclick=()=>{revealed=!revealed;renderCards();};bind({flip:()=>{revealed=true;renderCards();},again:()=>gradeCard(false),got:()=>gradeCard(true),skill:()=>startSession(card.unit)});}
function gradeCard(ok){const c=card,p=state.cards[c.id]||{run:0};p.run=ok?p.run+1:0;p.due=ok?Date.now()+[5*60000,86400000,3*86400000,7*86400000][Math.min(p.run-1,3)]:Date.now();state.cards[c.id]=p;cardQueue.shift();if(!ok)cardQueue.splice(Math.min(2,cardQueue.length),0,c);card=null;revealed=false;save();renderCards();}
async function loadAudio(){try{const r=await fetch('audio/manifest.json',{cache:'no-cache'});if(!r.ok)return;const data=await r.json();if(Array.isArray(data.tracks))manifest=data;}catch{}}
function renderListen(){app.innerHTML=`<section class="narrow"><span class="eyebrow">TAKE THE LESSON WITH YOU</span><h1 style="font-size:45px">Listen. Think.<br>Say it back.</h1><p>Patient narration, worked examples, and built-in pauses to answer out loud. Generated MP3s play in the audio player and can be downloaded.</p>${manifest?`<div class="card side-note"><h3>The complete study walk</h3><p>One continuous audio file. No need to return to the app between lessons.</p>${button('Play all lessons','allAudio','primary')}</div>`:`<div class="card side-note"><h3>Your narration is ready to generate</h3><p>The lesson scripts are ready. OpenAI MP3 audio has not been generated yet. You can read every script now or use the device voice while this page stays open.</p><a href="https://github.com/mikyewh67/codex/blob/main/AUDIO_SETUP.md" target="_blank" rel="noopener">Set up the private audio key ↗</a></div>`}<div style="display:grid;gap:14px;margin-top:22px">${AUDIO_LESSONS.map(l=>{const track=manifest?.tracks.find(t=>t.id===l.id);return `<div class="card track" id="track-${l.id}"><span class="track-icon">♫</span><div><h3>${esc(l.title)}</h3><p>${esc(l.subtitle)}</p><div class="track-actions">${track?`<button class="btn primary" data-play="${l.id}">Play MP3 · ${Math.ceil(track.duration/60)} min</button>`:`<button class="btn" data-device="${l.id}">Device voice</button>`}<button class="btn quiet" data-transcript="${l.id}">Read script</button></div></div></div>`;}).join('')}</div><p class="source">AI-generated narration, not your professor’s voice. Screen-lock behavior depends on your browser and device; downloadable MP3s also work in an audio player. Device voice requires keeping the page open.</p><div class="card"><h3>Your video reference</h3><p>The linked video is an 11-hour financial accounting course. Your focused lessons use the professor transcripts you supplied; the full YouTube video has not been transcribed here.</p><a href="https://www.youtube.com/watch?v=eyXKvOrDoqw" target="_blank" rel="noopener">Open the full YouTube course ↗</a></div></section>`;bind({allAudio:()=>playAudio('complete')});app.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>playAudio(b.dataset.play));app.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>speakDevice(b.dataset.device));app.querySelectorAll('[data-transcript]').forEach(b=>b.onclick=()=>renderTranscript(b.dataset.transcript));}
function renderTranscript(id){const l=AUDIO_LESSONS.find(l=>l.id===id);app.innerHTML=`<section class="narrow"><button class="back" data-action="back">← Audio lessons</button><span class="eyebrow">READ & FOLLOW</span><h2>${esc(l.title)}</h2><div class="actions">${manifest?.tracks.find(t=>t.id===id)?button('Play narration','play','primary'):button('Read with device voice','device','primary')}${button('Stop device voice','stop')}</div><div class="transcript">${l.segments.map((s,i)=>`<p data-segment="${i}">${esc(s.text)}${s.pause?`<br><em>Pause and answer · ${s.pause} seconds</em>`:''}</p>`).join('')}</div></section>`;app.dataset.transcript=id;bind({back:()=>nav('listen'),play:()=>playAudio(id),device:()=>speakDevice(id),stop:stopDeviceVoice});window.scrollTo(0,0);}
const audio=$('#lessonAudio');
function playAudio(id){const track=manifest?.tracks.find(t=>t.id===id);if(!track){toast('This audio has not been generated yet.');return;}stopDeviceVoice();playing=track;$('#playerDock').hidden=false;document.body.style.paddingBottom='220px';$('#playingTitle').textContent=track.title;$('#audioDownload').href=track.url;$('#audioDownload').download=id+'.mp3';$('#audioStatus').textContent='AI narration · Download for listening in your preferred audio player.';audio.src=track.url;audio.playbackRate=Number($('#audioSpeed').value);audio.play().catch(()=>$('#audioStatus').textContent='Tap Play in the audio controls to begin.');if('mediaSession' in navigator&&'MediaMetadata' in window){navigator.mediaSession.metadata=new MediaMetadata({title:track.title,artist:'Ledger Academy',album:'Accounting study walk'});}}
$('#closePlayer').onclick=()=>{audio.pause();$('#playerDock').hidden=true;document.body.style.paddingBottom='';};$('#rewind').onclick=()=>audio.currentTime=Math.max(0,audio.currentTime-15);$('#audioSpeed').onchange=e=>audio.playbackRate=Number(e.target.value);
audio.onerror=()=>$('#audioStatus').textContent='This audio could not load. Check your connection or regenerate the audio files.';
audio.ontimeupdate=()=>{if(!playing)return;if(app.dataset.transcript===playing.id&&playing.segments){const i=playing.segments.findIndex(s=>audio.currentTime>=s.start&&audio.currentTime<s.end);app.querySelectorAll('[data-segment]').forEach(p=>{p.style.color=Number(p.dataset.segment)===i?'var(--gold)':'';});}if('mediaSession'in navigator&&navigator.mediaSession.setPositionState&&Number.isFinite(audio.duration)){try{navigator.mediaSession.setPositionState({duration:audio.duration,playbackRate:audio.playbackRate,position:Math.min(audio.currentTime,audio.duration)});}catch{}}};
if('mediaSession'in navigator){for(const [action,handler] of Object.entries({play:()=>audio.play().catch(()=>{}),pause:()=>audio.pause(),seekbackward:()=>audio.currentTime=Math.max(0,audio.currentTime-15),seekforward:()=>audio.currentTime=Math.min(audio.duration||0,audio.currentTime+15),seekto:d=>audio.currentTime=d.seekTime})){try{navigator.mediaSession.setActionHandler(action,handler);}catch{}}}
let voiceToken=0,voiceTimer;
function stopDeviceVoice(){voiceToken++;clearTimeout(voiceTimer);window.speechSynthesis?.cancel();}
function speakDevice(id){if(!window.speechSynthesis){toast('Device voice is unavailable in this browser. Read the script instead.');return;}audio.pause();stopDeviceVoice();const token=voiceToken,l=AUDIO_LESSONS.find(x=>x.id===id);let i=0;function read(){if(token!==voiceToken||i>=l.segments.length)return;const segment=l.segments[i++],utter=new SpeechSynthesisUtterance(segment.text);utter.rate=.95;utter.onend=()=>voiceTimer=setTimeout(read,(segment.pause||.5)*1000);utter.onerror=()=>toast('Device voice stopped. Try the lesson again.');speechSynthesis.speak(utter);}read();toast('Device voice started. Keep this page open.');}
function exportProgress(){const blob=new Blob([JSON.stringify({version:1,state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ledger-academy-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function importProgress(e){try{const file=e.target.files[0];if(!file)return;if(file.size>1e6)throw Error();const data=JSON.parse(await file.text()),s=data.state;if(data.version!==1||!validState(s))throw Error();state={...empty(),...s};session=null;cardQueue=[];card=null;save();nav('path');toast('Progress restored.');}catch{toast('That file is not a valid Academy progress backup.');}}
document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>nav(b.dataset.view));save();nav('path');loadAudio().then(()=>{if(view==='listen')renderListen();});
