// Original teaching examples aligned with the existing Chapters 1–2 course map.
const money=n=>'$'+Number(n).toLocaleString('en-US');
export const TUTORIALS={
 foundations:{title:'Understand the business story',minutes:7,description:'Account types, financial statements, and when revenue is earned.',pages:[
  {title:'Every account tells you something different.',text:['Accounting tracks what a business owns, what it owes, and the owner’s claim. Each account is a named container for one kind of information. Cash holds the money balance; Accounts Receivable holds amounts customers still owe.','Start by classifying the account. A resource is an asset. An obligation to pay money or provide a service is a liability. Capital, withdrawals, revenue, and expenses explain the owner’s equity.'],visual:'classify',takeaway:'Receivable = customers owe the business. Payable = the business owes someone else.'},
  {title:'Four reports. Four different questions.',text:['An income statement explains performance over a period. A balance sheet shows financial position on one date. The statement of owner’s equity connects the owner’s beginning and ending claim.','The cash flow statement explains cash coming in and going out. Your Test #1 emphasis is preparing the income, owner’s equity, and balance sheet statements. Tap each report to see its purpose.'],visual:'statements',takeaway:'“For the month ended” covers a period. “As of” or a single date describes a snapshot.'},
  {title:'Cash and income are different stories.',text:['Revenue is earned by providing a service, even if the customer will pay later. Collecting an existing receivable is not another sale—you already recognized that revenue.','A customer payment for future work is an obligation to perform the work. Record Unearned Revenue (also called Unearned Fees), a liability, until the work is earned.'],visual:'recognition',takeaway:'Ask “Have we earned it?” before asking “Have we received the cash?”'},
  {title:'Owner activity is not operating performance.',text:['An owner investment increases capital. An owner withdrawal reduces equity. Neither belongs in the income statement.','If the owner invests $3,000, the business earns $2,000 of revenue, incurs $800 of expenses, and the owner withdraws $500, income is $1,200. The net increase in equity is $3,700.'],visual:'owner',takeaway:'Income = $2,000 − $800 = $1,200. Equity change = $3,000 + $1,200 − $500 = $3,700.'}
 ]},
 equations:{title:'Make the equation work for you',minutes:7,description:'See the balance, rearrange the formula, and solve missing amounts.',pages:[
  {title:'Assets have two sources of claims.',text:['Assets = Liabilities + Equity. Creditors have a claim through liabilities; the owner has the remaining claim through equity. Rearranging gives Equity = Assets − Liabilities.','In the visual, assets stay at $20,000. Move the liability amount to see how much of those assets remains as the owner’s claim. This compares different financial positions; it is not a transaction by itself.'],visual:'equation',takeaway:'To find a missing amount, write the equation first, substitute the known numbers, and then solve.'},
  {title:'Follow the changes in equity.',text:['Beginning Equity + Investment + Income − Withdrawals = Ending Equity. Investment and income add to equity; withdrawals reduce it. A net loss enters the equation as negative income.','Begin with $10,000. The owner invests $4,000, the business earns $3,000 of income, and the owner withdraws $2,000. Follow each step to reach $15,000 ending equity.'],visual:'equity-bridge',takeaway:'Keep investments and withdrawals separate from revenues and expenses.'},
  {title:'Solve backward for income.',text:['Some test questions give assets and liabilities at two dates, plus investment and withdrawals. First calculate equity at each date. Then use the equity-change equation to solve for income.','Example: beginning assets $28,000 and liabilities $8,000; ending assets $39,000 and liabilities $12,000; owner investment $5,000 and withdrawals $2,000. Reveal the solution one step at a time.'],visual:'reverse-income',takeaway:'Income = Ending Equity − Beginning Equity − Investment + Withdrawals.'}
 ]},
 'transaction-analysis':{title:'See what actually changes',minutes:8,description:'Financial position → accounts → recording plan.',pages:[
  {title:'One asset can replace another.',text:['A customer pays $3,000 of an existing receivable. Cash increases, but Accounts Receivable decreases by the same amount. The business has not earned a second round of revenue.','Move the collection slider. Watch the two asset balances change while total assets stay at $10,000. No liability or equity changes.'],visual:'collection',takeaway:'“Cash increased” does not automatically mean “total assets increased.”'},
  {title:'Use your professor’s three-step order.',text:['A business provides $2,400 of services on account. “On account” means the customer will pay later. The business has earned revenue and acquired a claim against the customer.','Work in order: financial position first, specific accounts second, then debit and credit. The journal entry is the final recording of that reasoning.'],visual:'analysis',takeaway:'For earned services on account: Assets ↑, Equity ↑; debit Accounts Receivable and credit Service Revenue.'},
  {title:'An advance payment creates an obligation.',text:['A client pays $2,000 before work is performed. The business receives cash but still owes the service: Assets ↑ and Liabilities ↑.','When the service is later provided, the obligation goes down and earned revenue increases equity. Cash does not change again at that point. Switch between the two events below.'],visual:'advance',takeaway:'Cash received early: Cash / Unearned Revenue. Work earned later: Unearned Revenue / Service Revenue.'}
 ]},
 'debits-credits':{title:'Make debit and credit click',minutes:6,description:'Learn the sides, normal balances, and increase/decrease rule.',pages:[
  {title:'Debit means left. Credit means right.',text:['Every T-account uses the same two sides: debit on the left, credit on the right. Those words do not, by themselves, mean increase or decrease.','The account type determines its normal balance—the side normally used for increases. Select an account and a direction to see which side records the change.'],visual:'normal',takeaway:'Increase → use the normal side. Decrease → use the opposite side.'},
  {title:'Remember the two groups.',text:['Assets, Withdrawals, and Expenses normally have debit balances. Liabilities, Capital, and Revenue normally have credit balances.','This is why Cash increases with a debit while Accounts Payable increases with a credit. Both are increases; their account types use different normal sides.'],visual:'normal-map',takeaway:'Your notes’ shortcut: A-W-E on the debit side. Liabilities, Capital, Revenue on the credit side.'},
  {title:'Paying a liability uses a debit.',text:['Accounts Payable has a $6,000 credit balance. The business pays $1,500 of that debt. Because a liability is decreasing, record a debit to Accounts Payable. Cash decreases with a credit.','The remaining Accounts Payable balance is $4,500 credit. A debit entry is not the same thing as a debit ending balance.'],visual:'liability',takeaway:'An unusual balance can signal an error. Accounts Payable normally ends with a credit balance.'}
 ]},
 journal:{title:'Turn the reasoning into an entry',minutes:8,description:'Read a journal entry, build compound entries, and avoid common swaps.',pages:[
  {title:'The layout carries meaning.',text:['A journal records transactions in date order. List debit accounts first. List credit accounts after them and indent their names. Put each amount in its own debit or credit column.','For $2,400 of services provided on account, Accounts Receivable is debited and Service Revenue is credited. The entry balances, but it also needs to use the right accounts.'],visual:'entry-anatomy',takeaway:'Correct accounts + correct sides + correct amounts + correct form.'},
  {title:'A compound entry still has one balance.',text:['A business buys equipment for $12,000. It pays $5,000 cash and promises to pay the seller $7,000 later. Equipment is recorded at the full $12,000 cost.','Assets increase $12,000 for equipment and decrease $5,000 for cash: net assets increase $7,000. Accounts Payable increases $7,000. Equity does not change.'],visual:'compound',takeaway:'One debit can balance two credits: $12,000 = $5,000 + $7,000.'},
  {title:'Similar cash movements can mean different things.',text:['Receiving cash could mean an owner investment, a new sale, collection of a receivable, a loan, or an advance from a customer. The cash account alone does not tell the whole story.','Choose a transaction below. Read what happened before looking at its journal entry. Notice how the credit account changes even though Cash is debited in each example.'],visual:'cash-patterns',takeaway:'Identify why the money moved. Do not pick the second account just because cash went up.'}
 ]},
 ledger:{title:'Watch entries become balances',minutes:7,description:'Post to T-accounts and calculate debit- or credit-normal balances.',pages:[
  {title:'Posting means copying to the account.',text:['The journal groups information by transaction. The ledger groups it by account. Posting copies the same debit or credit from the journal to the matching side of that account.','Here Cash begins at $5,000 debit. An investment adds $3,000, rent paid uses $1,000, and a withdrawal uses $500. Move through the postings and watch the running balance.'],visual:'posting',takeaway:'Left stays debit. Right stays credit. Posting does not reverse the entry.'},
  {title:'Choose the formula from the normal side.',text:['For a debit-normal asset: Beginning + Debits − Credits = Ending. For a credit-normal liability: Beginning + Credits − Debits = Ending.','A/R begins at $3,800. Services on account add $6,400 and collections remove $6,900, leaving $3,300. A/P begins at $1,200. Purchases on account add $4,800 and payments remove $3,500, leaving $2,500.'],visual:'balance-formulas',takeaway:'Add activity on the normal side; subtract activity on the opposite side.'},
  {title:'Find a missing posting amount.',text:['Accounts Receivable begins at $6,000. Services on account total $9,000. Ending Accounts Receivable is $4,000. How much cash was collected?','Collections reduce A/R with a credit. Use Beginning + Debits = Ending + Credits, then isolate the unknown.'],visual:'missing-collections',takeaway:'Collections = $6,000 + $9,000 − $4,000 = $11,000. Collections are not new revenue.'}
 ]},
 'trial-balance':{title:'Bring all the accounts together',minutes:7,description:'Place balances correctly and understand what balancing can prove.',pages:[
  {title:'A trial balance collects ledger balances.',text:['After posting transactions and calculating each account balance, list those ending balances in a trial balance. Each account appears on its actual balance side.','Use your course order: assets, liabilities, then capital, withdrawals, revenues, and expenses. These are balances—not every individual journal posting.'],visual:'trial-order',takeaway:'Do not put withdrawals under expenses. Both normally have debit balances, but they have different meanings.'},
  {title:'Add the two columns separately.',text:['The example trial balance for Harbor Consulting has $32,000 of debit balances and $32,000 of credit balances. Assets total $25,000; they are only part of the debit column.','Withdrawals and expenses also have debit balances. The credit column contains liabilities, capital, and revenue. Select a group to highlight where it appears.'],visual:'trial-table',takeaway:'Total trial-balance debits are not the same as total assets.'},
  {title:'Balanced does not always mean correct.',text:['If only the debit side of a $500 transaction is posted, the totals will differ. But omitting the entire transaction leaves both totals equal.','Recording a $500 owner investment as Service Revenue instead of Capital also leaves the trial balance balanced. The accounts are wrong even though the sides match.'],visual:'errors',takeaway:'Check both arithmetic and account meaning. Equal columns catch some errors, not all errors.'}
 ]},
 'financial-statements':{title:'Build the three statements',minutes:9,description:'Follow one company from trial balance to income, equity, and financial position.',pages:[
  {title:'Begin with the trial balance.',text:['We will use Harbor Consulting’s September 30 trial balance to prepare all three statements. Its $15,000 Capital balance includes $12,000 beginning capital and $3,000 invested in September.','Prepare the Income Statement first, the Statement of Owner’s Equity second, and the Balance Sheet third. Income flows into equity; ending equity flows into the balance sheet.'],visual:'statement-flow',takeaway:'The sequence is about shared numbers: net income first, ending equity next, then financial position.'},
  {title:'1. Calculate income for the period.',text:['The income statement includes revenues and expenses. Harbor earned $9,000 of service revenue and incurred $4,000 of wages expense and $2,000 of rent expense.','Total expenses are $6,000, so net income is $3,000. The $1,000 withdrawal is excluded because it is an owner distribution, not an expense.'],visual:'income-statement',takeaway:'Revenue − Expenses = Income. The heading covers a period, not a single instant.'},
  {title:'2. Explain the change in owner’s equity.',text:['Begin with $12,000 capital on September 1. Add the $3,000 owner investment and the $3,000 net income from the income statement. Subtract the $1,000 withdrawal.','Ending capital is $17,000. Do not add the investment to the $15,000 trial-balance Capital figure a second time—it is already included there.'],visual:'equity-statement',takeaway:'Either start with $12,000 and add investment, or start with the $15,000 unclosed Capital balance. Do not count investment twice.'},
  {title:'3. Show the ending financial position.',text:['The balance sheet reports assets, liabilities, and ending owner’s equity as of September 30. Harbor has $25,000 of assets and $8,000 of liabilities.','Bring over $17,000 ending capital from the equity statement. Assets $25,000 = Liabilities $8,000 + Equity $17,000. Revenue, expenses, and withdrawals are not separate balance-sheet lines.'],visual:'balance-sheet',takeaway:'The statements connect: $3,000 income → $17,000 ending capital → a balanced $25,000 balance sheet.'}
 ]}
};
export function topicForQuestion(q){
 const g=q?.generator||'';
 if(/^(normal-balance|increase-decrease-side|abnormal-balance)$/.test(g))return 'debits-credits';
 if(/^(balance-|missing-|posting-concept)/.test(g))return 'ledger';
 if(/^(journal-|multi-journal|test-journal)/.test(g))return 'journal';
 if(/^(effect-|multi-effects)/.test(g))return 'transaction-analysis';
 if(/^(trial-summary|statement-order|capital-balance-trap)$/.test(g))return 'financial-statements';
 if(/^(account-classify|definition|statement-identify)$/.test(g))return 'foundations';
 return TUTORIALS[q?.section]?q.section:'foundations';
}
const balances=[['Cash',12000,'Dr','Assets'],['Accounts Receivable',4000,'Dr','Assets'],['Supplies',1000,'Dr','Assets'],['Equipment',8000,'Dr','Assets'],['Accounts Payable',3000,'Cr','Liabilities'],['Notes Payable',5000,'Cr','Liabilities'],['Capital',15000,'Cr','Capital'],['Withdrawals',1000,'Dr','Withdrawals'],['Service Revenue',9000,'Cr','Revenue'],['Wages Expense',4000,'Dr','Expenses'],['Rent Expense',2000,'Dr','Expenses']];
const row=(a,b,cls='')=>`<div class="statement-row ${cls}"><span>${a}</span><strong>${b}</strong></div>`;
const equation=(a,b,c)=>`<div class="equation-cards"><div><small>ASSETS</small><strong>${money(a)}</strong></div><b>=</b><div><small>LIABILITIES</small><strong>${money(b)}</strong></div><b>+</b><div><small>EQUITY</small><strong>${money(c)}</strong></div></div>`;
const journal=rows=>`<div class="tutorial-table-wrap"><table class="tutorial-table"><thead><tr><th scope="col">Account</th><th scope="col">Debit</th><th scope="col">Credit</th></tr></thead><tbody>${rows.map(([a,d,c])=>`<tr><td class="${c?'entry-credit':''}">${a}</td><td>${d?money(d):'—'}</td><td>${c?money(c):'—'}</td></tr>`).join('')}</tbody></table></div>`;
const taccount=(name,dr,cr)=>`<div class="t-account"><h4>${name}</h4><div class="t-sides"><div><small>DEBIT · LEFT</small>${dr.map(v=>`<span>${v}</span>`).join('')}</div><div><small>CREDIT · RIGHT</small>${cr.map(v=>`<span>${v}</span>`).join('')}</div></div></div>`;
const stepper=(steps)=>`<div class="worked-steps" data-walkthrough>${steps.map(([a,b],i)=>`<div class="worked-step" ${i?'hidden':''}><span>${i+1}</span><div><h4>${a}</h4><div class="worked-detail">${b}</div></div></div>`).join('')}<button class="btn btn-light" data-reveal>Show next step</button><span class="step-count" aria-live="polite">1 of ${steps.length} steps</span></div>`;
const statement=(name,period,content)=>`<div class="paper-statement"><div class="statement-heading"><strong>Harbor Consulting</strong><h4>${name}</h4><span>${period}</span></div>${content}</div>`;
const period='For the Month Ended September 30, 2026';
export function renderVisual(kind){
 switch(kind){
 case 'classify':return `<label class="visual-label" for="accountDemo">Choose an account</label><select id="accountDemo"><option>Cash</option><option>Accounts Receivable</option><option>Accounts Payable</option><option>Unearned Revenue</option><option>Capital</option><option>Withdrawals</option><option>Service Revenue</option><option>Rent Expense</option></select><div id="classifyResult" class="visual-result" aria-live="polite"></div>`;
 case 'statements':return `<div class="visual-tabs" role="group" aria-label="Financial statement"><button class="active" data-report="income">Income</button><button data-report="equity">Equity</button><button data-report="balance">Balance sheet</button><button data-report="cash">Cash flows</button></div><div id="reportResult" class="visual-result" aria-live="polite"></div>`;
 case 'recognition':return `<div class="story-timeline"><article><span>01 · WORK EARNED</span><h4>Provide $2,000 of services on account</h4>${journal([['Accounts Receivable',2000,0],['Service Revenue',0,2000]])}<p>Revenue is recognized now. Cash has not arrived.</p></article><article><span>02 · MONEY COLLECTED</span><h4>Collect that same $2,000 later</h4>${journal([['Cash',2000,0],['Accounts Receivable',0,2000]])}<p>Cash replaces the receivable. No new revenue.</p></article></div>`;
 case 'owner':return `<div class="compare-panels"><div><span class="eyebrow">OPERATIONS → INCOME</span>${row('Revenue','+ $2,000')}${row('Expenses','− $800')}${row('Net income','$1,200','total')}</div><div><span class="eyebrow">OWNER + OPERATIONS → EQUITY</span>${row('Investment','+ $3,000')}${row('Net income','+ $1,200')}${row('Withdrawals','− $500')}${row('Equity increase','$3,700','total')}</div></div>`;
 case 'equation':return `<label class="visual-label" for="liabilityDemo">Change liabilities (assets stay at $20,000)</label><input id="liabilityDemo" type="range" min="0" max="20000" step="1000" value="8000"><div id="equationResult" aria-live="polite"></div>`;
 case 'equity-bridge':return stepper([['Beginning equity','$10,000 is the starting balance.'],['Add owner investment','$10,000 + $4,000 = $14,000. This is not revenue.'],['Add income','$14,000 + $3,000 = $17,000.'],['Subtract withdrawals','$17,000 − $2,000 = $15,000 ending equity.']]);
 case 'reverse-income':return stepper([['Beginning equity','$28,000 assets − $8,000 liabilities = $20,000.'],['Ending equity','$39,000 assets − $12,000 liabilities = $27,000.'],['Set up the equity equation','$20,000 + $5,000 + Income − $2,000 = $27,000.'],['Isolate income','Income = $27,000 − $20,000 − $5,000 + $2,000 = $4,000.']]);
 case 'collection':return `<div class="asset-bars"><div><span>Cash</span><div><i id="cashBar"></i></div><strong id="cashValue"></strong></div><div><span>A/R</span><div><i id="arBar"></i></div><strong id="arValue"></strong></div></div><label class="visual-label" for="collectionDemo">Amount collected: <output id="collectionValue">$0</output></label><input type="range" id="collectionDemo" min="0" max="3000" value="0" step="500"><div class="visual-summary" aria-live="polite">Total assets <strong>$10,000</strong><span>No change to liabilities or equity.</span></div>`;
 case 'analysis':return stepper([['Financial position','Services earned on account increase assets $2,400 and equity $2,400.'],['Identify the accounts','Accounts Receivable increases because the customer owes us. Service Revenue increases because we earned it.'],['Make the recording plan','A/R is an asset: increase with a debit. Revenue increases with a credit.'],['Journalize',journal([['Accounts Receivable',2400,0],['Service Revenue',0,2400]])]]);
 case 'advance':return `<div class="visual-tabs" role="group" aria-label="Advance payment events"><button class="active" data-advance="receive">1. Receive cash</button><button data-advance="earn">2. Earn the service</button></div><div id="advanceResult" class="visual-result" aria-live="polite"></div>`;
 case 'normal':return `<div class="demo-controls"><label>Account<select id="normalAccount"><option value="Cash">Cash · Asset</option><option value="Accounts Payable">Accounts Payable · Liability</option><option value="Capital">Capital · Equity</option><option value="Withdrawals">Withdrawals</option><option value="Service Revenue">Service Revenue</option><option value="Rent Expense">Rent Expense</option></select></label><label>Direction<select id="normalDirection"><option value="increase">Increase</option><option value="decrease">Decrease</option></select></label></div><div id="normalResult" aria-live="polite"></div>`;
 case 'normal-map':return `<div class="normal-map"><div><span>DEBIT NORMAL</span><h4>A · W · E</h4><p>Assets<br>Withdrawals<br>Expenses</p><small>Increase: Debit<br>Decrease: Credit</small></div><div><span>CREDIT NORMAL</span><h4>L · C · R</h4><p>Liabilities<br>Capital<br>Revenue</p><small>Increase: Credit<br>Decrease: Debit</small></div></div>`;
 case 'liability':return taccount('Accounts Payable',['Payment $1,500'],['Beginning $6,000'])+`<div class="visual-summary">$6,000 credit − $1,500 debit<strong>$4,500 credit balance</strong></div>`+journal([['Accounts Payable',1500,0],['Cash',0,1500]]);
 case 'entry-anatomy':return `<span class="visual-label">SEPTEMBER 5 · SERVICES EARNED ON ACCOUNT</span>${journal([['Accounts Receivable',2400,0],['Service Revenue',0,2400]])}<div class="entry-key"><span><b>01</b> Debit first</span><span><b>02</b> Credit indented</span><span><b>03</b> Equal totals</span></div><div class="visual-summary">Total debits = Total credits<strong>$2,400 = $2,400</strong></div>`;
 case 'compound':return stepper([['Record the full asset','Equipment increases $12,000 → Debit Equipment $12,000.'],['Record the cash paid','Cash decreases $5,000 → Credit Cash $5,000.'],['Record the remaining obligation','Accounts Payable increases $7,000 → Credit Accounts Payable $7,000.'],['Check the completed entry',journal([['Equipment',12000,0],['Cash',0,5000],['Accounts Payable',0,7000]])+'Total debits $12,000 = total credits $12,000.']]);
 case 'cash-patterns':return `<label class="visual-label" for="cashPattern">Why did the business receive $2,000?</label><select id="cashPattern"><option value="sale">Services earned for cash</option><option value="collect">Collection on account</option><option value="advance">Customer advance</option><option value="invest">Owner investment</option><option value="borrow">Bank loan</option></select><div id="cashPatternResult" aria-live="polite"></div>`;
 case 'posting':return `<div id="postingResult" aria-live="polite"></div><div class="visual-tabs"><button data-post="prev">← Previous posting</button><button data-post="next">Next posting →</button></div>`;
 case 'balance-formulas':return `<div class="compare-panels"><div><span class="eyebrow">DEBIT-NORMAL · A/R</span><p>Beginning + Debits − Credits</p>${row('Beginning','$3,800')}${row('Services on account','+ $6,400')}${row('Collections','− $6,900')}${row('Ending A/R','$3,300 Dr','total')}</div><div><span class="eyebrow">CREDIT-NORMAL · A/P</span><p>Beginning + Credits − Debits</p>${row('Beginning','$1,200')}${row('Purchases on account','+ $4,800')}${row('Payments','− $3,500')}${row('Ending A/P','$2,500 Cr','total')}</div></div>`;
 case 'missing-collections':return stepper([['Write the balance relationship','Beginning A/R + Services on account = Ending A/R + Collections.'],['Substitute what you know','$6,000 + $9,000 = $4,000 + Collections.'],['Solve','$15,000 − $4,000 = $11,000 collections.'],['Check','$6,000 + $9,000 − $11,000 = $4,000 ending A/R.']]);
 case 'trial-order':return `<ol class="account-order">${[['Assets','Cash, A/R, Supplies, Equipment','Dr'],['Liabilities','A/P, Notes Payable, Unearned Fees','Cr'],['Capital','Owner’s capital','Cr'],['Withdrawals','Owner’s withdrawals','Dr'],['Revenue','Service Revenue / Fees Earned','Cr'],['Expenses','Wages, Rent, Utilities','Dr']].map(([a,b,c],i)=>`<li><span>0${i+1}</span><div><strong>${a}</strong><small>${b}</small></div><b>${c}</b></li>`).join('')}</ol><p class="visual-note">Dr/Cr here shows the normal side. Use the actual balance side if an account has an abnormal balance.</p>`;
 case 'trial-table':return `<label class="visual-label" for="trialGroup">Highlight an account group</label><select id="trialGroup"><option value="All">All accounts</option>${['Assets','Liabilities','Capital','Withdrawals','Revenue','Expenses'].map(a=>`<option>${a}</option>`).join('')}</select><div class="tutorial-table-wrap"><table class="tutorial-table"><caption>Harbor Consulting · Trial Balance · September 30, 2026</caption><thead><tr><th>Account</th><th>Debit</th><th>Credit</th></tr></thead><tbody>${balances.map(([a,n,side,g])=>`<tr data-group="${g}"><td>${a}</td><td>${side==='Dr'?money(n):'—'}</td><td>${side==='Cr'?money(n):'—'}</td></tr>`).join('')}</tbody><tfoot><tr><th>Total</th><td>$32,000</td><td>$32,000</td></tr></tfoot></table></div><div id="trialGroupResult" class="visual-note" aria-live="polite"></div>`;
 case 'errors':return `<div class="error-examples"><article><span class="badge bad">UNBALANCED</span><h4>Only one side was posted</h4><p>Debit Cash $500, but forget the credit.</p><strong>Debit total is $500 higher.</strong></article><article><span class="badge warn">BALANCED, BUT WRONG</span><h4>The entire entry was omitted</h4><p>Neither the $500 debit nor the $500 credit is recorded.</p><strong>Equal totals do not detect this.</strong></article><article><span class="badge warn">BALANCED, BUT WRONG</span><h4>The wrong account was credited</h4><p>Credit Revenue instead of Capital for an investment.</p><strong>Income is overstated by $500.</strong></article></div>`;
 case 'statement-flow':return `<div class="statement-path"><article><span>01 · INCOME STATEMENT</span><h4>$3,000 net income</h4><p>$9,000 revenue − $6,000 expenses</p></article><div>↓ Net income moves here</div><article><span>02 · OWNER’S EQUITY</span><h4>$17,000 ending capital</h4><p>$12,000 + $3,000 + $3,000 − $1,000</p></article><div>↓ Ending capital moves here</div><article><span>03 · BALANCE SHEET</span><h4>$25,000 = $8,000 + $17,000</h4><p>Assets = Liabilities + Equity</p></article></div><details class="tutorial-source"><summary>View the starting trial balance</summary>${renderVisual('trial-table')}</details>`;
 case 'income-statement':return statement('Income Statement',period,row('Service Revenue','$9,000')+row('Expenses','')+row('Wages Expense','$4,000','indent')+row('Rent Expense','$2,000','indent')+row('Total Expenses','$6,000','subtotal')+row('Net Income','$3,000','total'));
 case 'equity-statement':return statement('Statement of Owner’s Equity',period,row('Capital, September 1','$12,000')+row('Add: Owner Investment','$3,000')+row('Add: Net Income','$3,000')+row('Subtotal','$18,000','subtotal')+row('Less: Withdrawals','($1,000)')+row('Capital, September 30','$17,000','total'));
 case 'balance-sheet':return statement('Balance Sheet','September 30, 2026',`<h5>ASSETS</h5>`+row('Cash','$12,000')+row('Accounts Receivable','$4,000')+row('Supplies','$1,000')+row('Equipment','$8,000')+row('Total Assets','$25,000','total')+'<h5>LIABILITIES</h5>'+row('Accounts Payable','$3,000')+row('Notes Payable','$5,000')+row('Total Liabilities','$8,000','subtotal')+'<h5>OWNER’S EQUITY</h5>'+row('Capital, September 30','$17,000')+row('Total Liabilities & Equity','$25,000','total'));
 default:return '';
 }
}
function activeButtons(root,selector,selected){root.querySelectorAll(selector).forEach(b=>{const on=b===selected;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});}
export function wireVisual(root,kind){
 const $=s=>root.querySelector(s);
 if(kind==='statement-flow')wireVisual(root,'trial-table');
 root.querySelectorAll('[data-walkthrough]').forEach(box=>{let index=1;const steps=[...box.querySelectorAll('.worked-step')],button=box.querySelector('[data-reveal]');button.onclick=()=>{if(index>=steps.length){steps.forEach((el,i)=>el.hidden=i>0);index=1;button.textContent='Show next step';}else{steps[index++].hidden=false;if(index===steps.length)button.textContent='Replay walkthrough';}box.querySelector('.step-count').textContent=`${index} of ${steps.length} steps`;};});
 if(kind==='classify'){
 const data={'Cash':['Asset','Money the business owns.','Debit'],'Accounts Receivable':['Asset','A customer owes money to the business.','Debit'],'Accounts Payable':['Liability','The business owes money to a supplier.','Credit'],'Unearned Revenue':['Liability','The business owes a service it has not yet earned.','Credit'],'Capital':['Owner’s equity','The owner’s recorded capital. Investments increase it.','Credit'],'Withdrawals':['Withdrawals','Resources taken out by the owner; reduces equity.','Debit'],'Service Revenue':['Revenue','Value earned from performing services; increases equity.','Credit'],'Rent Expense':['Expense','A cost incurred in operations; reduces equity.','Debit']};
 const update=()=>{const [type,reason,normal]=data[$('#accountDemo').value];$('#classifyResult').innerHTML=`<span class="visual-label">${$('#accountDemo').value}</span><h4>${type}</h4><p>${reason}</p><span class="badge warn">Normal balance: ${normal}</span>`;};$('#accountDemo').onchange=update;update();
 }
 if(kind==='statements'){
 const data={income:['Did we earn a profit?','For a period','Revenue $9,000 − Expenses $6,000 = Income $3,000.'],equity:['Why did the owner’s claim change?','For a period','Beginning + Investment + Income − Withdrawals = Ending Equity.'],balance:['What do we own and owe?','At one date','Assets $25,000 = Liabilities $8,000 + Equity $17,000.'],cash:['Where did cash come from and go?','For a period','Beginning Cash + Cash Inflows − Cash Outflows = Ending Cash.']};
 const update=b=>{const [q,date,formula]=data[b.dataset.report];activeButtons(root,'[data-report]',b);$('#reportResult').innerHTML=`<span class="visual-label">${date}</span><h4>${q}</h4><p>${formula}</p>`;};root.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>update(b));update($('[data-report]'));
 }
 if(kind==='equation'){const update=()=>{const l=Number($('#liabilityDemo').value);$('#equationResult').innerHTML=equation(20000,l,20000-l)+`<div class="funding-bar"><span style="width:${l/200}%">${l?'L':''}</span><span style="width:${(20000-l)/200}%">${l<20000?'E':''}</span></div><p class="visual-note">Creditors: ${money(l)} · Owner: ${money(20000-l)}</p>`;};$('#liabilityDemo').oninput=update;update();}
 if(kind==='collection'){const update=()=>{const amount=Number($('#collectionDemo').value);$('#cashBar').style.width=(4000+amount)/100+'%';$('#arBar').style.width=(6000-amount)/100+'%';$('#cashValue').textContent=money(4000+amount);$('#arValue').textContent=money(6000-amount);$('#collectionValue').textContent=money(amount);};$('#collectionDemo').oninput=update;update();}
 if(kind==='advance'){const update=b=>{activeButtons(root,'[data-advance]',b);const earn=b.dataset.advance==='earn';$('#advanceResult').innerHTML=`<h4>${earn?'Liabilities ↓ · Equity ↑':'Assets ↑ · Liabilities ↑'}</h4>${journal(earn?[['Unearned Revenue',2000,0],['Service Revenue',0,2000]]:[['Cash',2000,0],['Unearned Revenue',0,2000]])}<p>${earn?'The obligation is fulfilled. No additional cash changes hands.':'Cash arrives now, but the service is still owed.'}</p>`;};root.querySelectorAll('[data-advance]').forEach(b=>b.onclick=()=>update(b));update($('[data-advance]'));}
 if(kind==='normal'){const debit=['Cash','Withdrawals','Rent Expense'];const update=()=>{const account=$('#normalAccount').value,normal=debit.includes(account)?'Debit':'Credit',increase=$('#normalDirection').value==='increase',side=increase?normal:normal==='Debit'?'Credit':'Debit';$('#normalResult').innerHTML=taccount(account,side==='Debit'?['← Record here']:['—'],side==='Credit'?['Record here →']:['—'])+`<div class="visual-summary">Normal side: ${normal}<strong>${increase?'Increase':'Decrease'} → ${side}</strong><span>${increase?'Use the normal side.':'Use the opposite side.'}</span></div>`;};$('#normalAccount').onchange=update;$('#normalDirection').onchange=update;update();}
 if(kind==='cash-patterns'){const map={sale:['Service Revenue','Revenue is earned now.'],collect:['Accounts Receivable','Reduce the customer’s existing debt. No new revenue.'],advance:['Unearned Revenue','The business still owes the future service.'],invest:['Capital','Owner investment increases capital, not revenue.'],borrow:['Notes Payable','Borrowing creates a liability, not revenue.']};const update=()=>{const [account,why]=map[$('#cashPattern').value];$('#cashPatternResult').innerHTML=journal([['Cash',2000,0],[account,0,2000]])+`<p class="visual-note">${why}</p>`;};$('#cashPattern').onchange=update;update();}
 if(kind==='posting'){let i=0;const events=['Beginning balance','Owner invests $3,000','Pay $1,000 rent','Owner withdraws $500'];const update=()=>{const dr=['Beginning $5,000',...(i>=1?['Investment $3,000']:[])],cr=[...(i>=2?['Rent $1,000']:[]),...(i>=3?['Withdrawal $500']:[])];$('#postingResult').innerHTML=`<span class="visual-label">${i} / 3 POSTINGS · ${events[i]}</span>${taccount('Cash',dr,cr.length?cr:['—'])}<div class="visual-summary">Running debit balance<strong>${money(5000+(i>=1?3000:0)-(i>=2?1000:0)-(i>=3?500:0))}</strong></div>`;$('[data-post="prev"]').disabled=i===0;$('[data-post="next"]').disabled=i===3;};$('[data-post="prev"]').onclick=()=>{i--;update();};$('[data-post="next"]').onclick=()=>{i++;update();};update();}
 if(kind==='trial-table'){const update=()=>{const group=$('#trialGroup').value;root.querySelectorAll('[data-group]').forEach(tr=>tr.classList.toggle('row-highlight',group!=='All'&&tr.dataset.group===group));const total=balances.filter(x=>group==='All'||x[3]===group).reduce((a,x)=>a+x[1],0);$('#trialGroupResult').textContent=group==='All'?'Debit total $32,000 = Credit total $32,000.':`${group}: ${money(total)} in ${['Assets','Withdrawals','Expenses'].includes(group)?'debit':'credit'} balances.`;};$('#trialGroup').onchange=update;update();}
}
